openapi: 3.2.0
info:
  title: Commerce Layer Event Stores API
  version: 7.10.1
  contact:
    name: API Support
    url: https://commercelayer.io
    email: support@commercelayer.io
  description: Headless Commerce for Global Brands.
servers:
- url: https://{your_organization_slug}.commercelayer.io/api
  description: API
- url: https://core.commercelayer.io/users/sign_in
  description: Sign in
- url: https://docs.commercelayer.io/api
  description: API reference
security:
- bearerAuth: []
tags:
- name: event_stores
  description: resource type
paths:
  /event_stores/{eventStoreId}:
    get:
      operationId: GET/event_stores/eventStoreId
      summary: Retrieve an event store
      description: Retrieve an event store
      tags:
      - event_stores
      parameters:
      - name: eventStoreId
        in: path
        schema:
          type: string
        required: true
        description: The resource's id
      responses:
        '200':
          description: The event store object
          content:
            application/vnd.api+json:
              schema:
                $ref: '#/components/schemas/eventStoreResponse'
components:
  schemas:
    eventStore:
      type: object
      properties:
        data:
          type: object
          required:
          - type
          - attributes
          properties:
            type:
              type: string
              description: The resource's type
              enum:
              - event_stores
            attributes:
              type: object
              properties:
                resource_type:
                  type: string
                  description: The type of the affected resource.
                  example: orders
                  nullable: true
                resource_id:
                  type: string
                  description: The ID of the affected resource.
                  example: PzdJhdLdYV
                  nullable: true
                event:
                  type: string
                  description: The type of change (one of create or update).
                  example: update
                  nullable: true
                payload:
                  type: object
                  description: The object changes payload.
                  example:
                    status:
                    - draft
                    - placed
                  nullable: true
                who:
                  type: object
                  description: Information about who triggered the change.
                  example:
                    application:
                      id: DNOPYiZYpn
                      kind: sales_channel
                      public: true
                    owner:
                      id: yQQrBhLBmQ
                      type: Customer
                  nullable: true
                created_at:
                  type: string
                  description: Time at which the resource was created.
                  example: '2018-01-01T12:00:00.000Z'
                  nullable: false
                updated_at:
                  type: string
                  description: Time at which the resource was last updated.
                  example: '2018-01-01T12:00:00.000Z'
                  nullable: false
                reference:
                  type: string
                  description: A string that you can use to add any external identifier to the resource. This can be useful for integrating the resource to an external system, like an ERP, a marketing tool, a CRM, or whatever.
                  example: ANY-EXTERNAL-REFEFERNCE
                  nullable: true
                reference_origin:
                  type: string
                  description: Any identifier of the third party system that defines the reference code.
                  example: ANY-EXTERNAL-REFEFERNCE-ORIGIN
                  nullable: true
                metadata:
                  type: object
                  description: Set of key-value pairs that you can attach to the resource. This can be useful for storing additional information about the resource in a structured format.
                  example:
                    foo: bar
                  nullable: true
            relationships:
              type: object
              properties: {}
    eventStoreResponse:
      type: object
      properties:
        data:
          type: object
          properties:
            id:
              type: string
              description: The event identifier.
              example: 1755185525941-0
            type:
              type: string
              description: The resource's type
              enum:
              - event_stores
            links:
              type: object
              properties:
                self:
                  type: string
                  description: URL
            attributes:
              $ref: '#/components/schemas/eventStore/properties/data/properties/attributes'
            relationships:
              type: object
              properties: {}
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
