openapi: 3.2.0
info:
  title: Commerce Layer Klarna Gateways API
  version: 7.10.1
  contact:
    name: API Support
    url: https://commercelayer.io
    email: support@commercelayer.io
  description: Headless Commerce for Global Brands.
servers:
- url: https://{your_organization_slug}.commercelayer.io/api
  description: API
- url: https://core.commercelayer.io/users/sign_in
  description: Sign in
- url: https://docs.commercelayer.io/api
  description: API reference
security:
- bearerAuth: []
tags:
- name: klarna_gateways
  description: resource type
paths:
  /klarna_gateways:
    get:
      operationId: GET/klarna_gateways
      summary: List all klarna gateways
      description: List all klarna gateways
      tags:
      - klarna_gateways
      responses:
        '200':
          description: A list of klarna gateway objects
          content:
            application/vnd.api+json:
              schema:
                $ref: '#/components/schemas/klarnaGatewayResponseList'
    post:
      operationId: POST/klarna_gateways
      summary: Create a klarna gateway
      description: Create a klarna gateway
      tags:
      - klarna_gateways
      requestBody:
        required: true
        content:
          application/vnd.api+json:
            schema:
              $ref: '#/components/schemas/klarnaGatewayCreate'
      responses:
        '201':
          description: The created klarna gateway object
          content:
            application/vnd.api+json:
              schema:
                $ref: '#/components/schemas/klarnaGatewayResponse'
  /klarna_gateways/{klarnaGatewayId}:
    get:
      operationId: GET/klarna_gateways/klarnaGatewayId
      summary: Retrieve a klarna gateway
      description: Retrieve a klarna gateway
      tags:
      - klarna_gateways
      parameters:
      - name: klarnaGatewayId
        in: path
        schema:
          type: string
        required: true
        description: The resource's id
      responses:
        '200':
          description: The klarna gateway object
          content:
            application/vnd.api+json:
              schema:
                $ref: '#/components/schemas/klarnaGatewayResponse'
    patch:
      operationId: PATCH/klarna_gateways/klarnaGatewayId
      summary: Update a klarna gateway
      description: Update a klarna gateway
      tags:
      - klarna_gateways
      parameters:
      - name: klarnaGatewayId
        in: path
        schema:
          type: string
        required: true
        description: The resource's id
      requestBody:
        required: true
        content:
          application/vnd.api+json:
            schema:
              $ref: '#/components/schemas/klarnaGatewayUpdate'
      responses:
        '200':
          description: The updated klarna gateway object
          content:
            application/vnd.api+json:
              schema:
                $ref: '#/components/schemas/klarnaGatewayResponse'
    delete:
      operationId: DELETE/klarna_gateways/klarnaGatewayId
      summary: Delete a klarna gateway
      description: Delete a klarna gateway
      tags:
      - klarna_gateways
      parameters:
      - name: klarnaGatewayId
        in: path
        schema:
          type: string
        required: true
        description: The resource's id
      responses:
        '204':
          description: No content
components:
  schemas:
    klarnaGatewayResponse:
      type: object
      properties:
        data:
          type: object
          properties:
            id:
              type: string
              description: Unique identifier for the resource (hash).
              example: XAyRWNUzyN
            type:
              type: string
              description: The resource's type
              enum:
              - klarna_gateways
            links:
              type: object
              properties:
                self:
                  type: string
                  description: URL
            attributes:
              $ref: '#/components/schemas/klarnaGateway/properties/data/properties/attributes'
            relationships:
              type: object
              properties:
                payment_methods:
                  type: object
                  properties:
                    links:
                      type: object
                      properties:
                        self:
                          type: string
                          description: URL
                        related:
                          type: string
                          description: URL
                    data:
                      type: object
                      properties:
                        type:
                          type: string
                          description: The resource's type
                          enum:
                          - payment_methods
                        id:
                          type: string
                          description: The resource ID
                event_stores:
                  type: object
                  properties:
                    links:
                      type: object
                      properties:
                        self:
                          type: string
                          description: URL
                        related:
                          type: string
                          description: URL
                    data:
                      type: object
                      properties:
                        type:
                          type: string
                          description: The resource's type
                          enum:
                          - event_stores
                        id:
                          type: string
                          description: The resource ID
                klarna_payments:
                  type: object
                  properties:
                    links:
                      type: object
                      properties:
                        self:
                          type: string
                          description: URL
                        related:
                          type: string
                          description: URL
                    data:
                      type: object
                      properties:
                        type:
                          type: string
                          description: The resource's type
                          enum:
                          - klarna_payments
                        id:
                          type: string
                          description: The resource ID
    klarnaGatewayResponseList:
      type: object
      properties:
        data:
          type: array
          items:
            $ref: '#/components/schemas/klarnaGatewayResponse/properties/data'
    klarnaGatewayCreate:
      required:
      - data
      type: object
      properties:
        data:
          type: object
          required:
          - type
          - attributes
          properties:
            type:
              type: string
              description: The resource's type
              enum:
              - klarna_gateways
            attributes:
              type: object
              properties:
                name:
                  type: string
                  description: The payment gateway's internal name.
                  example: US payment gateway
                force_payments:
                  type: boolean
                  description: Indicates if the payment source is forced on the editable order upon receiving a successful event from the gateway.
                  example: true
                _disable:
                  type: boolean
                  description: Send this attribute if you want to mark this resource as disabled.
                  example: true
                _enable:
                  type: boolean
                  description: Send this attribute if you want to mark this resource as enabled.
                  example: true
                reference:
                  type: string
                  description: A string that you can use to add any external identifier to the resource. This can be useful for integrating the resource to an external system, like an ERP, a marketing tool, a CRM, or whatever.
                  example: ANY-EXTERNAL-REFEFERNCE
                reference_origin:
                  type: string
                  description: Any identifier of the third party system that defines the reference code.
                  example: ANY-EXTERNAL-REFEFERNCE-ORIGIN
                metadata:
                  type: object
                  description: Set of key-value pairs that you can attach to the resource. This can be useful for storing additional information about the resource in a structured format.
                  example:
                    foo: bar
                country_code:
                  type: string
                  description: The gateway country code one of EU, US, or OC.
                  example: EU
                api_key:
                  type: string
                  description: The public key linked to your API credential.
                  example: xxxx-yyyy-zzzz
                api_secret:
                  type: string
                  description: The gateway API key.
                  example: xxxx-yyyy-zzzz
              required:
              - name
              - country_code
              - api_key
              - api_secret
            relationships:
              type: object
              properties:
                klarna_payments:
                  required:
                  - data
                  type: object
                  properties:
                    data:
                      type: object
                      properties:
                        type:
                          type: string
                          description: The resource's type
                          enum:
                          - klarna_payments
                        id:
                          type: string
                          description: Unique identifier for the resource (hash).
                          example: XAyRWNUzyN
    klarnaGatewayUpdate:
      required:
      - data
      type: object
      properties:
        data:
          type: object
          required:
          - type
          - id
          - attributes
          properties:
            type:
              type: string
              description: The resource's type
              enum:
              - klarna_gateways
            id:
              type: string
              description: Unique identifier for the resource (hash).
              example: XAyRWNUzyN
            attributes:
              type: object
              properties:
                name:
                  type: string
                  description: The payment gateway's internal name.
                  example: US payment gateway
                  nullable: false
                force_payments:
                  type: boolean
                  description: Indicates if the payment source is forced on the editable order upon receiving a successful event from the gateway.
                  example: true
                  nullable: false
                _disable:
                  type: boolean
                  description: Send this attribute if you want to mark this resource as disabled.
                  example: true
                  nullable: false
                _enable:
                  type: boolean
                  description: Send this attribute if you want to mark this resource as enabled.
                  example: true
                  nullable: false
                reference:
                  type: string
                  description: A string that you can use to add any external identifier to the resource. This can be useful for integrating the resource to an external system, like an ERP, a marketing tool, a CRM, or whatever.
                  example: ANY-EXTERNAL-REFEFERNCE
                  nullable: true
                reference_origin:
                  type: string
                  description: Any identifier of the third party system that defines the reference code.
                  example: ANY-EXTERNAL-REFEFERNCE-ORIGIN
                  nullable: true
                metadata:
                  type: object
                  description: Set of key-value pairs that you can attach to the resource. This can be useful for storing additional information about the resource in a structured format.
                  example:
                    foo: bar
                  nullable: true
                country_code:
                  type: string
                  description: The gateway country code one of EU, US, or OC.
                  example: EU
                api_key:
                  type: string
                  description: The public key linked to your API credential.
                  example: xxxx-yyyy-zzzz
                api_secret:
                  type: string
                  description: The gateway API key.
                  example: xxxx-yyyy-zzzz
            relationships:
              type: object
              properties:
                klarna_payments:
                  required:
                  - data
                  type: object
                  properties:
                    data:
                      type: object
                      properties:
                        type:
                          type: string
                          description: The resource's type
                          enum:
                          - klarna_payments
                        id:
                          type: string
                          description: Unique identifier for the resource (hash).
                          example: XAyRWNUzyN
    klarnaGateway:
      type: object
      properties:
        data:
          type: object
          required:
          - type
          - attributes
          properties:
            type:
              type: string
              description: The resource's type
              enum:
              - klarna_gateways
            attributes:
              type: object
              properties:
                name:
                  type: string
                  description: The payment gateway's internal name.
                  example: US payment gateway
                  nullable: false
                force_payments:
                  type: boolean
                  description: Indicates if the payment source is forced on the editable order upon receiving a successful event from the gateway.
                  example: true
                  nullable: true
                credential_keys:
                  type: object
                  description: The payment gateway's API credential keys last digits.
                  example:
                    api_key: '********BW989'
                  nullable: true
                disabled_at:
                  type: string
                  description: Time at which this resource was disabled.
                  example: '2018-01-01T12:00:00.000Z'
                  nullable: true
                created_at:
                  type: string
                  description: Time at which the resource was created.
                  example: '2018-01-01T12:00:00.000Z'
                  nullable: false
                updated_at:
                  type: string
                  description: Time at which the resource was last updated.
                  example: '2018-01-01T12:00:00.000Z'
                  nullable: false
                reference:
                  type: string
                  description: A string that you can use to add any external identifier to the resource. This can be useful for integrating the resource to an external system, like an ERP, a marketing tool, a CRM, or whatever.
                  example: ANY-EXTERNAL-REFEFERNCE
                  nullable: true
                reference_origin:
                  type: string
                  description: Any identifier of the third party system that defines the reference code.
                  example: ANY-EXTERNAL-REFEFERNCE-ORIGIN
                  nullable: true
                metadata:
                  type: object
                  description: Set of key-value pairs that you can attach to the resource. This can be useful for storing additional information about the resource in a structured format.
                  example:
                    foo: bar
                  nullable: true
            relationships:
              type: object
              properties:
                payment_methods:
                  type: object
                  properties:
                    data:
                      type: object
                      properties:
                        type:
                          type: string
                          description: The resource's type
                          enum:
                          - payment_methods
                        id:
                          type: string
                          description: Unique identifier for the resource (hash).
                          example: XAyRWNUzyN
                event_stores:
                  type: object
                  properties:
                    data:
                      type: object
                      properties:
                        type:
                          type: string
                          description: The resource's type
                          enum:
                          - event_stores
                        id:
                          type: string
                          description: Unique identifier for the resource (hash).
                          example: XAyRWNUzyN
                klarna_payments:
                  type: object
                  properties:
                    data:
                      type: object
                      properties:
                        type:
                          type: string
                          description: The resource's type
                          enum:
                          - klarna_payments
                        id:
                          type: string
                          description: Unique identifier for the resource (hash).
                          example: XAyRWNUzyN
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
