openapi: 3.2.0
info:
  title: Commerce Layer Customer Password Resets API
  version: 7.10.1
  contact:
    name: API Support
    url: https://commercelayer.io
    email: support@commercelayer.io
  description: Headless Commerce for Global Brands.
servers:
- url: https://{your_organization_slug}.commercelayer.io/api
  description: API
- url: https://core.commercelayer.io/users/sign_in
  description: Sign in
- url: https://docs.commercelayer.io/api
  description: API reference
security:
- bearerAuth: []
tags:
- name: customer_password_resets
  description: resource type
paths:
  /customer_password_resets:
    get:
      operationId: GET/customer_password_resets
      summary: List all customer password resets
      description: List all customer password resets
      tags:
      - customer_password_resets
      responses:
        '200':
          description: A list of customer password reset objects
          content:
            application/vnd.api+json:
              schema:
                $ref: '#/components/schemas/customerPasswordResetResponseList'
    post:
      operationId: POST/customer_password_resets
      summary: Create a customer password reset
      description: Create a customer password reset
      tags:
      - customer_password_resets
      requestBody:
        required: true
        content:
          application/vnd.api+json:
            schema:
              $ref: '#/components/schemas/customerPasswordResetCreate'
      responses:
        '201':
          description: The created customer password reset object
          content:
            application/vnd.api+json:
              schema:
                $ref: '#/components/schemas/customerPasswordResetResponse'
  /customer_password_resets/{customerPasswordResetId}:
    get:
      operationId: GET/customer_password_resets/customerPasswordResetId
      summary: Retrieve a customer password reset
      description: Retrieve a customer password reset
      tags:
      - customer_password_resets
      parameters:
      - name: customerPasswordResetId
        in: path
        schema:
          type: string
        required: true
        description: The resource's id
      responses:
        '200':
          description: The customer password reset object
          content:
            application/vnd.api+json:
              schema:
                $ref: '#/components/schemas/customerPasswordResetResponse'
    patch:
      operationId: PATCH/customer_password_resets/customerPasswordResetId
      summary: Update a customer password reset
      description: Update a customer password reset
      tags:
      - customer_password_resets
      parameters:
      - name: customerPasswordResetId
        in: path
        schema:
          type: string
        required: true
        description: The resource's id
      requestBody:
        required: true
        content:
          application/vnd.api+json:
            schema:
              $ref: '#/components/schemas/customerPasswordResetUpdate'
      responses:
        '200':
          description: The updated customer password reset object
          content:
            application/vnd.api+json:
              schema:
                $ref: '#/components/schemas/customerPasswordResetResponse'
    delete:
      operationId: DELETE/customer_password_resets/customerPasswordResetId
      summary: Delete a customer password reset
      description: Delete a customer password reset
      tags:
      - customer_password_resets
      parameters:
      - name: customerPasswordResetId
        in: path
        schema:
          type: string
        required: true
        description: The resource's id
      responses:
        '204':
          description: No content
components:
  schemas:
    customerPasswordResetResponse:
      type: object
      properties:
        data:
          type: object
          properties:
            id:
              type: string
              description: Unique identifier for the resource (hash).
              example: XAyRWNUzyN
            type:
              type: string
              description: The resource's type
              enum:
              - customer_password_resets
            links:
              type: object
              properties:
                self:
                  type: string
                  description: URL
            attributes:
              $ref: '#/components/schemas/customerPasswordReset/properties/data/properties/attributes'
            relationships:
              type: object
              properties:
                customer:
                  type: object
                  properties:
                    links:
                      type: object
                      properties:
                        self:
                          type: string
                          description: URL
                        related:
                          type: string
                          description: URL
                    data:
                      type: object
                      properties:
                        type:
                          type: string
                          description: The resource's type
                          enum:
                          - customer
                        id:
                          type: string
                          description: The resource ID
                events:
                  type: object
                  properties:
                    links:
                      type: object
                      properties:
                        self:
                          type: string
                          description: URL
                        related:
                          type: string
                          description: URL
                    data:
                      type: object
                      properties:
                        type:
                          type: string
                          description: The resource's type
                          enum:
                          - events
                        id:
                          type: string
                          description: The resource ID
                event_stores:
                  type: object
                  properties:
                    links:
                      type: object
                      properties:
                        self:
                          type: string
                          description: URL
                        related:
                          type: string
                          description: URL
                    data:
                      type: object
                      properties:
                        type:
                          type: string
                          description: The resource's type
                          enum:
                          - event_stores
                        id:
                          type: string
                          description: The resource ID
    customerPasswordResetCreate:
      required:
      - data
      type: object
      properties:
        data:
          type: object
          required:
          - type
          - attributes
          properties:
            type:
              type: string
              description: The resource's type
              enum:
              - customer_password_resets
            attributes:
              type: object
              properties:
                customer_email:
                  type: string
                  description: The email of the customer that requires a password reset.
                  example: john@example.com
                reference:
                  type: string
                  description: A string that you can use to add any external identifier to the resource. This can be useful for integrating the resource to an external system, like an ERP, a marketing tool, a CRM, or whatever.
                  example: ANY-EXTERNAL-REFEFERNCE
                reference_origin:
                  type: string
                  description: Any identifier of the third party system that defines the reference code.
                  example: ANY-EXTERNAL-REFEFERNCE-ORIGIN
                metadata:
                  type: object
                  description: Set of key-value pairs that you can attach to the resource. This can be useful for storing additional information about the resource in a structured format.
                  example:
                    foo: bar
              required:
              - customer_email
            relationships:
              type: object
              properties: {}
    customerPasswordReset:
      type: object
      properties:
        data:
          type: object
          required:
          - type
          - attributes
          properties:
            type:
              type: string
              description: The resource's type
              enum:
              - customer_password_resets
            attributes:
              type: object
              properties:
                customer_email:
                  type: string
                  description: The email of the customer that requires a password reset.
                  example: john@example.com
                  nullable: false
                reset_password_token:
                  type: string
                  description: Automatically generated on create. Send its value as the '_reset_password_token' argument when updating the customer password.
                  example: xhFfkmfybsLxzaAP6xcs
                  nullable: true
                reset_password_at:
                  type: string
                  description: Time at which the password was reset.
                  example: '2018-01-01T12:00:00.000Z'
                  nullable: true
                created_at:
                  type: string
                  description: Time at which the resource was created.
                  example: '2018-01-01T12:00:00.000Z'
                  nullable: false
                updated_at:
                  type: string
                  description: Time at which the resource was last updated.
                  example: '2018-01-01T12:00:00.000Z'
                  nullable: false
                reference:
                  type: string
                  description: A string that you can use to add any external identifier to the resource. This can be useful for integrating the resource to an external system, like an ERP, a marketing tool, a CRM, or whatever.
                  example: ANY-EXTERNAL-REFEFERNCE
                  nullable: true
                reference_origin:
                  type: string
                  description: Any identifier of the third party system that defines the reference code.
                  example: ANY-EXTERNAL-REFEFERNCE-ORIGIN
                  nullable: true
                metadata:
                  type: object
                  description: Set of key-value pairs that you can attach to the resource. This can be useful for storing additional information about the resource in a structured format.
                  example:
                    foo: bar
                  nullable: true
            relationships:
              type: object
              properties:
                customer:
                  type: object
                  properties:
                    data:
                      type: object
                      properties:
                        type:
                          type: string
                          description: The resource's type
                          enum:
                          - customers
                        id:
                          type: string
                          description: Unique identifier for the resource (hash).
                          example: XAyRWNUzyN
                events:
                  type: object
                  properties:
                    data:
                      type: object
                      properties:
                        type:
                          type: string
                          description: The resource's type
                          enum:
                          - events
                        id:
                          type: string
                          description: Unique identifier for the resource (hash).
                          example: XAyRWNUzyN
                event_stores:
                  type: object
                  properties:
                    data:
                      type: object
                      properties:
                        type:
                          type: string
                          description: The resource's type
                          enum:
                          - event_stores
                        id:
                          type: string
                          description: Unique identifier for the resource (hash).
                          example: XAyRWNUzyN
    customerPasswordResetResponseList:
      type: object
      properties:
        data:
          type: array
          items:
            $ref: '#/components/schemas/customerPasswordResetResponse/properties/data'
    customerPasswordResetUpdate:
      required:
      - data
      type: object
      properties:
        data:
          type: object
          required:
          - type
          - id
          - attributes
          properties:
            type:
              type: string
              description: The resource's type
              enum:
              - customer_password_resets
            id:
              type: string
              description: Unique identifier for the resource (hash).
              example: XAyRWNUzyN
            attributes:
              type: object
              properties:
                customer_password:
                  type: string
                  description: The customer new password. This will be accepted only if a valid '_reset_password_token' is sent with the request.
                  example: secret
                _reset_password_token:
                  type: string
                  description: Send the 'reset_password_token' that you got on create when updating the customer password.
                  example: xhFfkmfybsLxzaAP6xcs
                reference:
                  type: string
                  description: A string that you can use to add any external identifier to the resource. This can be useful for integrating the resource to an external system, like an ERP, a marketing tool, a CRM, or whatever.
                  example: ANY-EXTERNAL-REFEFERNCE
                  nullable: true
                reference_origin:
                  type: string
                  description: Any identifier of the third party system that defines the reference code.
                  example: ANY-EXTERNAL-REFEFERNCE-ORIGIN
                  nullable: true
                metadata:
                  type: object
                  description: Set of key-value pairs that you can attach to the resource. This can be useful for storing additional information about the resource in a structured format.
                  example:
                    foo: bar
                  nullable: true
            relationships:
              type: object
              properties: {}
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
