openapi: 3.1.0
info:
  title: Commerce Layer addresses bing_geocoders API
  version: 7.10.1
  contact:
    name: API Support
    url: https://commercelayer.io
    email: support@commercelayer.io
  description: Headless Commerce for Global Brands.
servers:
- url: https://{your_organization_slug}.commercelayer.io/api
  description: API
- url: https://core.commercelayer.io/users/sign_in
  description: Sign in
- url: https://docs.commercelayer.io/api
  description: API reference
security:
- bearerAuth: []
tags:
- name: bing_geocoders
  description: resource type
paths:
  /bing_geocoders:
    get:
      operationId: GET/bing_geocoders
      summary: List all bing geocoders
      description: List all bing geocoders
      tags:
      - bing_geocoders
      responses:
        '200':
          description: A list of bing geocoder objects
          content:
            application/vnd.api+json:
              schema:
                $ref: '#/components/schemas/bingGeocoderResponseList'
    post:
      operationId: POST/bing_geocoders
      summary: Create a bing geocoder
      description: Create a bing geocoder
      tags:
      - bing_geocoders
      requestBody:
        required: true
        content:
          application/vnd.api+json:
            schema:
              $ref: '#/components/schemas/bingGeocoderCreate'
      responses:
        '201':
          description: The created bing geocoder object
          content:
            application/vnd.api+json:
              schema:
                $ref: '#/components/schemas/bingGeocoderResponse'
  /bing_geocoders/{bingGeocoderId}:
    get:
      operationId: GET/bing_geocoders/bingGeocoderId
      summary: Retrieve a bing geocoder
      description: Retrieve a bing geocoder
      tags:
      - bing_geocoders
      parameters:
      - name: bingGeocoderId
        in: path
        schema:
          type: string
        required: true
        description: The resource's id
      responses:
        '200':
          description: The bing geocoder object
          content:
            application/vnd.api+json:
              schema:
                $ref: '#/components/schemas/bingGeocoderResponse'
    patch:
      operationId: PATCH/bing_geocoders/bingGeocoderId
      summary: Update a bing geocoder
      description: Update a bing geocoder
      tags:
      - bing_geocoders
      parameters:
      - name: bingGeocoderId
        in: path
        schema:
          type: string
        required: true
        description: The resource's id
      requestBody:
        required: true
        content:
          application/vnd.api+json:
            schema:
              $ref: '#/components/schemas/bingGeocoderUpdate'
      responses:
        '200':
          description: The updated bing geocoder object
          content:
            application/vnd.api+json:
              schema:
                $ref: '#/components/schemas/bingGeocoderResponse'
    delete:
      operationId: DELETE/bing_geocoders/bingGeocoderId
      summary: Delete a bing geocoder
      description: Delete a bing geocoder
      tags:
      - bing_geocoders
      parameters:
      - name: bingGeocoderId
        in: path
        schema:
          type: string
        required: true
        description: The resource's id
      responses:
        '204':
          description: No content
components:
  schemas:
    bingGeocoderResponseList:
      type: object
      properties:
        data:
          type: array
          items:
            $ref: '#/components/schemas/bingGeocoderResponse/properties/data'
    bingGeocoderResponse:
      type: object
      properties:
        data:
          type: object
          properties:
            id:
              type: string
              description: Unique identifier for the resource (hash).
              example: XAyRWNUzyN
            type:
              type: string
              description: The resource's type
              enum:
              - bing_geocoders
            links:
              type: object
              properties:
                self:
                  type: string
                  description: URL
            attributes:
              $ref: '#/components/schemas/bingGeocoder/properties/data/properties/attributes'
            relationships:
              type: object
              properties:
                markets:
                  type: object
                  properties:
                    links:
                      type: object
                      properties:
                        self:
                          type: string
                          description: URL
                        related:
                          type: string
                          description: URL
                    data:
                      type: object
                      properties:
                        type:
                          type: string
                          description: The resource's type
                          enum:
                          - markets
                        id:
                          type: string
                          description: The resource ID
                addresses:
                  type: object
                  properties:
                    links:
                      type: object
                      properties:
                        self:
                          type: string
                          description: URL
                        related:
                          type: string
                          description: URL
                    data:
                      type: object
                      properties:
                        type:
                          type: string
                          description: The resource's type
                          enum:
                          - addresses
                        id:
                          type: string
                          description: The resource ID
                attachments:
                  type: object
                  properties:
                    links:
                      type: object
                      properties:
                        self:
                          type: string
                          description: URL
                        related:
                          type: string
                          description: URL
                    data:
                      type: object
                      properties:
                        type:
                          type: string
                          description: The resource's type
                          enum:
                          - attachments
                        id:
                          type: string
                          description: The resource ID
                event_stores:
                  type: object
                  properties:
                    links:
                      type: object
                      properties:
                        self:
                          type: string
                          description: URL
                        related:
                          type: string
                          description: URL
                    data:
                      type: object
                      properties:
                        type:
                          type: string
                          description: The resource's type
                          enum:
                          - event_stores
                        id:
                          type: string
                          description: The resource ID
    bingGeocoderUpdate:
      required:
      - data
      type: object
      properties:
        data:
          type: object
          required:
          - type
          - id
          - attributes
          properties:
            type:
              type: string
              description: The resource's type
              enum:
              - bing_geocoders
            id:
              type: string
              description: Unique identifier for the resource (hash).
              example: XAyRWNUzyN
            attributes:
              type: object
              properties:
                name:
                  type: string
                  description: The geocoder's internal name.
                  example: Default geocoder
                  nullable: false
                reference:
                  type: string
                  description: A string that you can use to add any external identifier to the resource. This can be useful for integrating the resource to an external system, like an ERP, a marketing tool, a CRM, or whatever.
                  example: ANY-EXTERNAL-REFEFERNCE
                  nullable: true
                reference_origin:
                  type: string
                  description: Any identifier of the third party system that defines the reference code.
                  example: ANY-EXTERNAL-REFEFERNCE-ORIGIN
                  nullable: true
                metadata:
                  type: object
                  description: Set of key-value pairs that you can attach to the resource. This can be useful for storing additional information about the resource in a structured format.
                  example:
                    foo: bar
                  nullable: true
                key:
                  type: string
                  description: The Bing Virtualearth key.
                  example: xxxx-yyyy-zzzz
            relationships:
              type: object
              properties: {}
    bingGeocoderCreate:
      required:
      - data
      type: object
      properties:
        data:
          type: object
          required:
          - type
          - attributes
          properties:
            type:
              type: string
              description: The resource's type
              enum:
              - bing_geocoders
            attributes:
              type: object
              properties:
                name:
                  type: string
                  description: The geocoder's internal name.
                  example: Default geocoder
                reference:
                  type: string
                  description: A string that you can use to add any external identifier to the resource. This can be useful for integrating the resource to an external system, like an ERP, a marketing tool, a CRM, or whatever.
                  example: ANY-EXTERNAL-REFEFERNCE
                reference_origin:
                  type: string
                  description: Any identifier of the third party system that defines the reference code.
                  example: ANY-EXTERNAL-REFEFERNCE-ORIGIN
                metadata:
                  type: object
                  description: Set of key-value pairs that you can attach to the resource. This can be useful for storing additional information about the resource in a structured format.
                  example:
                    foo: bar
                key:
                  type: string
                  description: The Bing Virtualearth key.
                  example: xxxx-yyyy-zzzz
              required:
              - name
              - key
            relationships:
              type: object
              properties: {}
    bingGeocoder:
      properties:
        data:
          properties:
            attributes:
              type: object
              properties:
                name:
                  type: string
                  description: The geocoder's internal name.
                  example: Default geocoder
                  nullable: false
                type:
                  type: string
                  description: The geocoder's type.
                  example: google_geocoders
                  nullable: false
                  enum:
                  - google_geocoders
                  - bing_geocoders
                created_at:
                  type: string
                  description: Time at which the resource was created.
                  example: '2018-01-01T12:00:00.000Z'
                  nullable: false
                updated_at:
                  type: string
                  description: Time at which the resource was last updated.
                  example: '2018-01-01T12:00:00.000Z'
                  nullable: false
                reference:
                  type: string
                  description: A string that you can use to add any external identifier to the resource. This can be useful for integrating the resource to an external system, like an ERP, a marketing tool, a CRM, or whatever.
                  example: ANY-EXTERNAL-REFEFERNCE
                  nullable: true
                reference_origin:
                  type: string
                  description: Any identifier of the third party system that defines the reference code.
                  example: ANY-EXTERNAL-REFEFERNCE-ORIGIN
                  nullable: true
                metadata:
                  type: object
                  description: Set of key-value pairs that you can attach to the resource. This can be useful for storing additional information about the resource in a structured format.
                  example:
                    foo: bar
                  nullable: true
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
