openapi: 3.1.0
info:
  title: Commerce Layer addresses sku_list_items API
  version: 7.10.1
  contact:
    name: API Support
    url: https://commercelayer.io
    email: support@commercelayer.io
  description: Headless Commerce for Global Brands.
servers:
- url: https://{your_organization_slug}.commercelayer.io/api
  description: API
- url: https://core.commercelayer.io/users/sign_in
  description: Sign in
- url: https://docs.commercelayer.io/api
  description: API reference
security:
- bearerAuth: []
tags:
- name: sku_list_items
  description: resource type
paths:
  /sku_list_items:
    get:
      operationId: GET/sku_list_items
      summary: List all SKU list items
      description: List all SKU list items
      tags:
      - sku_list_items
      responses:
        '200':
          description: A list of SKU list item objects
          content:
            application/vnd.api+json:
              schema:
                $ref: '#/components/schemas/skuListItemResponseList'
    post:
      operationId: POST/sku_list_items
      summary: Create a SKU list item
      description: Create a SKU list item
      tags:
      - sku_list_items
      requestBody:
        required: true
        content:
          application/vnd.api+json:
            schema:
              $ref: '#/components/schemas/skuListItemCreate'
      responses:
        '201':
          description: The created SKU list item object
          content:
            application/vnd.api+json:
              schema:
                $ref: '#/components/schemas/skuListItemResponse'
  /sku_list_items/{skuListItemId}:
    get:
      operationId: GET/sku_list_items/skuListItemId
      summary: Retrieve a SKU list item
      description: Retrieve a SKU list item
      tags:
      - sku_list_items
      parameters:
      - name: skuListItemId
        in: path
        schema:
          type: string
        required: true
        description: The resource's id
      responses:
        '200':
          description: The SKU list item object
          content:
            application/vnd.api+json:
              schema:
                $ref: '#/components/schemas/skuListItemResponse'
    patch:
      operationId: PATCH/sku_list_items/skuListItemId
      summary: Update a SKU list item
      description: Update a SKU list item
      tags:
      - sku_list_items
      parameters:
      - name: skuListItemId
        in: path
        schema:
          type: string
        required: true
        description: The resource's id
      requestBody:
        required: true
        content:
          application/vnd.api+json:
            schema:
              $ref: '#/components/schemas/skuListItemUpdate'
      responses:
        '200':
          description: The updated SKU list item object
          content:
            application/vnd.api+json:
              schema:
                $ref: '#/components/schemas/skuListItemResponse'
    delete:
      operationId: DELETE/sku_list_items/skuListItemId
      summary: Delete a SKU list item
      description: Delete a SKU list item
      tags:
      - sku_list_items
      parameters:
      - name: skuListItemId
        in: path
        schema:
          type: string
        required: true
        description: The resource's id
      responses:
        '204':
          description: No content
  /sku_lists/{skuListId}/sku_list_items:
    get:
      operationId: GET/skuListId/sku_list_items
      summary: Retrieve the sku list items associated to the SKU list
      description: Retrieve the sku list items associated to the SKU list
      tags:
      - sku_list_items
      parameters:
      - name: skuListId
        in: path
        schema:
          type: string
        required: true
        description: The resource's id
      responses:
        '200':
          description: The sku_list_items associated to the SKU list
  /skus/{skuId}/sku_list_items:
    get:
      operationId: GET/skuId/sku_list_items
      summary: Retrieve the sku list items associated to the SKU
      description: Retrieve the sku list items associated to the SKU
      tags:
      - sku_list_items
      parameters:
      - name: skuId
        in: path
        schema:
          type: string
        required: true
        description: The resource's id
      responses:
        '200':
          description: The sku_list_items associated to the SKU
components:
  schemas:
    skuListItemResponse:
      type: object
      properties:
        data:
          type: object
          properties:
            id:
              type: string
              description: Unique identifier for the resource (hash).
              example: XAyRWNUzyN
            type:
              type: string
              description: The resource's type
              enum:
              - sku_list_items
            links:
              type: object
              properties:
                self:
                  type: string
                  description: URL
            attributes:
              $ref: '#/components/schemas/skuListItem/properties/data/properties/attributes'
            relationships:
              type: object
              properties:
                sku_list:
                  type: object
                  properties:
                    links:
                      type: object
                      properties:
                        self:
                          type: string
                          description: URL
                        related:
                          type: string
                          description: URL
                    data:
                      type: object
                      properties:
                        type:
                          type: string
                          description: The resource's type
                          enum:
                          - sku_list
                        id:
                          type: string
                          description: The resource ID
                sku:
                  type: object
                  properties:
                    links:
                      type: object
                      properties:
                        self:
                          type: string
                          description: URL
                        related:
                          type: string
                          description: URL
                    data:
                      type: object
                      properties:
                        type:
                          type: string
                          description: The resource's type
                          enum:
                          - sku
                        id:
                          type: string
                          description: The resource ID
                event_stores:
                  type: object
                  properties:
                    links:
                      type: object
                      properties:
                        self:
                          type: string
                          description: URL
                        related:
                          type: string
                          description: URL
                    data:
                      type: object
                      properties:
                        type:
                          type: string
                          description: The resource's type
                          enum:
                          - event_stores
                        id:
                          type: string
                          description: The resource ID
    skuListItem:
      properties:
        data:
          properties:
            attributes:
              type: object
              properties:
                position:
                  type: integer
                  description: The SKU list item's position.
                  example: 2
                  nullable: true
                sku_code:
                  type: string
                  description: The code of the associated SKU.
                  example: TSHIRTMM000000FFFFFFXLXX
                  nullable: true
                quantity:
                  type: integer
                  description: The SKU quantity for this SKU list item.
                  example: 1
                  nullable: true
                created_at:
                  type: string
                  description: Time at which the resource was created.
                  example: '2018-01-01T12:00:00.000Z'
                  nullable: false
                updated_at:
                  type: string
                  description: Time at which the resource was last updated.
                  example: '2018-01-01T12:00:00.000Z'
                  nullable: false
                reference:
                  type: string
                  description: A string that you can use to add any external identifier to the resource. This can be useful for integrating the resource to an external system, like an ERP, a marketing tool, a CRM, or whatever.
                  example: ANY-EXTERNAL-REFEFERNCE
                  nullable: true
                reference_origin:
                  type: string
                  description: Any identifier of the third party system that defines the reference code.
                  example: ANY-EXTERNAL-REFEFERNCE-ORIGIN
                  nullable: true
                metadata:
                  type: object
                  description: Set of key-value pairs that you can attach to the resource. This can be useful for storing additional information about the resource in a structured format.
                  example:
                    foo: bar
                  nullable: true
    skuListItemResponseList:
      type: object
      properties:
        data:
          type: array
          items:
            $ref: '#/components/schemas/skuListItemResponse/properties/data'
    skuListItemCreate:
      required:
      - data
      type: object
      properties:
        data:
          type: object
          required:
          - type
          - attributes
          properties:
            type:
              type: string
              description: The resource's type
              enum:
              - sku_list_items
            attributes:
              type: object
              properties:
                position:
                  type: integer
                  description: The SKU list item's position.
                  example: 2
                sku_code:
                  type: string
                  description: The code of the associated SKU.
                  example: TSHIRTMM000000FFFFFFXLXX
                quantity:
                  type: integer
                  description: The SKU quantity for this SKU list item.
                  example: 1
                reference:
                  type: string
                  description: A string that you can use to add any external identifier to the resource. This can be useful for integrating the resource to an external system, like an ERP, a marketing tool, a CRM, or whatever.
                  example: ANY-EXTERNAL-REFEFERNCE
                reference_origin:
                  type: string
                  description: Any identifier of the third party system that defines the reference code.
                  example: ANY-EXTERNAL-REFEFERNCE-ORIGIN
                metadata:
                  type: object
                  description: Set of key-value pairs that you can attach to the resource. This can be useful for storing additional information about the resource in a structured format.
                  example:
                    foo: bar
            relationships:
              type: object
              properties:
                sku_list:
                  required:
                  - data
                  type: object
                  properties:
                    data:
                      type: object
                      properties:
                        type:
                          type: string
                          description: The resource's type
                          enum:
                          - sku_lists
                        id:
                          type: string
                          description: Unique identifier for the resource (hash).
                          example: XAyRWNUzyN
                sku:
                  required:
                  - data
                  type: object
                  properties:
                    data:
                      type: object
                      properties:
                        type:
                          type: string
                          description: The resource's type
                          enum:
                          - skus
                        id:
                          type: string
                          description: Unique identifier for the resource (hash).
                          example: XAyRWNUzyN
              required:
              - sku_list
              - sku
    skuListItemUpdate:
      required:
      - data
      type: object
      properties:
        data:
          type: object
          required:
          - type
          - id
          - attributes
          properties:
            type:
              type: string
              description: The resource's type
              enum:
              - sku_list_items
            id:
              type: string
              description: Unique identifier for the resource (hash).
              example: XAyRWNUzyN
            attributes:
              type: object
              properties:
                position:
                  type: integer
                  description: The SKU list item's position.
                  example: 2
                  nullable: true
                sku_code:
                  type: string
                  description: The code of the associated SKU.
                  example: TSHIRTMM000000FFFFFFXLXX
                  nullable: true
                quantity:
                  type: integer
                  description: The SKU quantity for this SKU list item.
                  example: 1
                  nullable: true
                reference:
                  type: string
                  description: A string that you can use to add any external identifier to the resource. This can be useful for integrating the resource to an external system, like an ERP, a marketing tool, a CRM, or whatever.
                  example: ANY-EXTERNAL-REFEFERNCE
                  nullable: true
                reference_origin:
                  type: string
                  description: Any identifier of the third party system that defines the reference code.
                  example: ANY-EXTERNAL-REFEFERNCE-ORIGIN
                  nullable: true
                metadata:
                  type: object
                  description: Set of key-value pairs that you can attach to the resource. This can be useful for storing additional information about the resource in a structured format.
                  example:
                    foo: bar
                  nullable: true
            relationships:
              type: object
              properties: {}
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
