openapi: 3.2.0
info:
  title: Commerce Layer Shipping Method Tiers API
  version: 7.10.1
  contact:
    name: API Support
    url: https://commercelayer.io
    email: support@commercelayer.io
  description: Headless Commerce for Global Brands.
servers:
- url: https://{your_organization_slug}.commercelayer.io/api
  description: API
- url: https://core.commercelayer.io/users/sign_in
  description: Sign in
- url: https://docs.commercelayer.io/api
  description: API reference
security:
- bearerAuth: []
tags:
- name: shipping_method_tiers
  description: resource type
paths:
  /shipping_method_tiers:
    get:
      operationId: GET/shipping_method_tiers
      summary: List all shipping method tiers
      description: List all shipping method tiers
      tags:
      - shipping_method_tiers
      responses:
        '200':
          description: A list of shipping method tier objects
          content:
            application/vnd.api+json:
              schema:
                $ref: '#/components/schemas/shippingMethodTierResponseList'
  /shipping_method_tiers/{shippingMethodTierId}:
    get:
      operationId: GET/shipping_method_tiers/shippingMethodTierId
      summary: Retrieve a shipping method tier
      description: Retrieve a shipping method tier
      tags:
      - shipping_method_tiers
      parameters:
      - name: shippingMethodTierId
        in: path
        schema:
          type: string
        required: true
        description: The resource's id
      responses:
        '200':
          description: The shipping method tier object
          content:
            application/vnd.api+json:
              schema:
                $ref: '#/components/schemas/shippingMethodTierResponse'
components:
  schemas:
    shippingMethodTier:
      type: object
      properties:
        data:
          type: object
          required:
          - type
          - attributes
          properties:
            type:
              type: string
              description: The resource's type
              enum:
              - shipping_method_tiers
            attributes:
              type: object
              properties:
                name:
                  type: string
                  description: The shipping method tier's name.
                  example: Light shipping under 3kg
                  nullable: false
                type:
                  type: string
                  description: The shipping method tier's type.
                  example: shipping_weight_tiers
                  nullable: false
                  enum:
                  - shipping_weight_tiers
                up_to:
                  type: number
                  description: The tier upper limit. When 'null' it means infinity (useful to have an always matching tier).
                  example: 20.5
                  nullable: true
                price_amount_cents:
                  type: integer
                  description: The price of this shipping method tier, in cents.
                  example: 1000
                  nullable: false
                price_amount_float:
                  type: number
                  description: The price of this shipping method tier, float.
                  example: 10.0
                  nullable: true
                formatted_price_amount:
                  type: string
                  description: The price of this shipping method tier, formatted.
                  example: €10,00
                  nullable: true
                created_at:
                  type: string
                  description: Time at which the resource was created.
                  example: '2018-01-01T12:00:00.000Z'
                  nullable: false
                updated_at:
                  type: string
                  description: Time at which the resource was last updated.
                  example: '2018-01-01T12:00:00.000Z'
                  nullable: false
                reference:
                  type: string
                  description: A string that you can use to add any external identifier to the resource. This can be useful for integrating the resource to an external system, like an ERP, a marketing tool, a CRM, or whatever.
                  example: ANY-EXTERNAL-REFEFERNCE
                  nullable: true
                reference_origin:
                  type: string
                  description: Any identifier of the third party system that defines the reference code.
                  example: ANY-EXTERNAL-REFEFERNCE-ORIGIN
                  nullable: true
                metadata:
                  type: object
                  description: Set of key-value pairs that you can attach to the resource. This can be useful for storing additional information about the resource in a structured format.
                  example:
                    foo: bar
                  nullable: true
            relationships:
              type: object
              properties:
                shipping_method:
                  type: object
                  properties:
                    data:
                      type: object
                      properties:
                        type:
                          type: string
                          description: The resource's type
                          enum:
                          - shipping_methods
                        id:
                          type: string
                          description: Unique identifier for the resource (hash).
                          example: XAyRWNUzyN
                attachments:
                  type: object
                  properties:
                    data:
                      type: object
                      properties:
                        type:
                          type: string
                          description: The resource's type
                          enum:
                          - attachments
                        id:
                          type: string
                          description: Unique identifier for the resource (hash).
                          example: XAyRWNUzyN
                event_stores:
                  type: object
                  properties:
                    data:
                      type: object
                      properties:
                        type:
                          type: string
                          description: The resource's type
                          enum:
                          - event_stores
                        id:
                          type: string
                          description: Unique identifier for the resource (hash).
                          example: XAyRWNUzyN
    shippingMethodTierResponse:
      type: object
      properties:
        data:
          type: object
          properties:
            id:
              type: string
              description: Unique identifier for the resource (hash).
              example: XAyRWNUzyN
            type:
              type: string
              description: The resource's type
              enum:
              - shipping_method_tiers
            links:
              type: object
              properties:
                self:
                  type: string
                  description: URL
            attributes:
              $ref: '#/components/schemas/shippingMethodTier/properties/data/properties/attributes'
            relationships:
              type: object
              properties:
                shipping_method:
                  type: object
                  properties:
                    links:
                      type: object
                      properties:
                        self:
                          type: string
                          description: URL
                        related:
                          type: string
                          description: URL
                    data:
                      type: object
                      properties:
                        type:
                          type: string
                          description: The resource's type
                          enum:
                          - shipping_method
                        id:
                          type: string
                          description: The resource ID
                attachments:
                  type: object
                  properties:
                    links:
                      type: object
                      properties:
                        self:
                          type: string
                          description: URL
                        related:
                          type: string
                          description: URL
                    data:
                      type: object
                      properties:
                        type:
                          type: string
                          description: The resource's type
                          enum:
                          - attachments
                        id:
                          type: string
                          description: The resource ID
                event_stores:
                  type: object
                  properties:
                    links:
                      type: object
                      properties:
                        self:
                          type: string
                          description: URL
                        related:
                          type: string
                          description: URL
                    data:
                      type: object
                      properties:
                        type:
                          type: string
                          description: The resource's type
                          enum:
                          - event_stores
                        id:
                          type: string
                          description: The resource ID
    shippingMethodTierResponseList:
      type: object
      properties:
        data:
          type: array
          items:
            $ref: '#/components/schemas/shippingMethodTierResponse/properties/data'
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
